baseurl = ""
languageCode = "en-us"
title = "Codefy"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "hpstrhugo"

[params]
	subtitle = "Tech Blog"
	[params.author]
		name = "Tiago Brenck"
		avatar = "/images/avatar.jpg"
		bio = ".NET Software Developer"
		github = "tiagobrenck"
	[params.image]
	  feature = "/images/hex-background.jpg"
